name: Build

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/sukawasatoru/toolchain-android-rust:1.0
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make release
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: target/**/rust-hello-android
